# Generated by Django 5.0.3 on 2024-05-20 05:36

import django.core.validators
import form.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('certificate in health science', 'Certificate in Health Science'), ('certificate in applied technology', 'Certificate in Applied Technology'), ('bachelor of inforamtion technology', 'Bachelor of Inforamtion Technology'), ('bachelor in business technology', 'Bachelor of Business Technology'), ('master of public health', 'Master of Public Health')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='entry_scheme',
            field=models.CharField(blank=True, choices=[('a-level certificate', 'A-Level Certificate'), ('adult/mature learning', 'Adult/Mature Learning'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelors', 'Bachelors')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3), form.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='intake',
            field=models.CharField(blank=True, choices=[('january intake', 'January Intake'), ('may intake', 'May Intake'), ('august intake', 'August')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3), form.models.validate_letters]),
        ),
        migrations.AlterField(
            model_name='student',
            name='residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsorship',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('government', 'Government'), ('bursary', 'Bursary')], max_length=50, null=True),
        ),
    ]
